const { up, down } = require("../../utils/uuid_v4_trigger");
const tableName = "countries";

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = async function (knex) {
  await knex.schema.createTable(tableName, function (table) {
    table.increments("id").primary();
    table.string("uuid_unique").unique().notNullable();
    table.string("name").notNullable();
    table.string("iso_alpha_2", 2).notNullable();
    table.string("iso_alpha_3", 3).notNullable().unique();
    table.integer("iso_numeric").notNullable();
    table.boolean("status").notNullable().defaultTo(true);
    table.timestamps(true, true);
  });

  await knex.raw(up(tableName));

  await knex(tableName).insert([
    {
      name: "Afghanistan",
      iso_alpha_2: "AF",
      iso_alpha_3: "AFG",
      iso_numeric: 4,
    },
    { name: "Albania", iso_alpha_2: "AL", iso_alpha_3: "ALB", iso_numeric: 8 },
    { name: "Algeria", iso_alpha_2: "DZ", iso_alpha_3: "DZA", iso_numeric: 12 },
    { name: "Andorra", iso_alpha_2: "AD", iso_alpha_3: "AND", iso_numeric: 20 },
    { name: "Angola", iso_alpha_2: "AO", iso_alpha_3: "AGO", iso_numeric: 24 },
    {
      name: "Argentina",
      iso_alpha_2: "AR",
      iso_alpha_3: "ARG",
      iso_numeric: 32,
    },
    { name: "Armenia", iso_alpha_2: "AM", iso_alpha_3: "ARM", iso_numeric: 51 },
    {
      name: "Australia",
      iso_alpha_2: "AU",
      iso_alpha_3: "AUS",
      iso_numeric: 36,
    },
    { name: "Austria", iso_alpha_2: "AT", iso_alpha_3: "AUT", iso_numeric: 40 },
    {
      name: "Azerbaijan",
      iso_alpha_2: "AZ",
      iso_alpha_3: "AZE",
      iso_numeric: 31,
    },
    { name: "Bahamas", iso_alpha_2: "BS", iso_alpha_3: "BHS", iso_numeric: 44 },
    { name: "Bahrain", iso_alpha_2: "BH", iso_alpha_3: "BHR", iso_numeric: 48 },
    {
      name: "Bangladesh",
      iso_alpha_2: "BD",
      iso_alpha_3: "BGD",
      iso_numeric: 50,
    },
    {
      name: "Barbados",
      iso_alpha_2: "BB",
      iso_alpha_3: "BRB",
      iso_numeric: 52,
    },
    {
      name: "Belarus",
      iso_alpha_2: "BY",
      iso_alpha_3: "BLR",
      iso_numeric: 112,
    },
    { name: "Belgium", iso_alpha_2: "BE", iso_alpha_3: "BEL", iso_numeric: 56 },
    { name: "Belize", iso_alpha_2: "BZ", iso_alpha_3: "BLZ", iso_numeric: 84 },
    { name: "Benin", iso_alpha_2: "BJ", iso_alpha_3: "BEN", iso_numeric: 204 },
    { name: "Bhutan", iso_alpha_2: "BT", iso_alpha_3: "BTN", iso_numeric: 64 },
    { name: "Bolivia", iso_alpha_2: "BO", iso_alpha_3: "BOL", iso_numeric: 68 },
    {
      name: "Bosnia and Herzegovina",
      iso_alpha_2: "BA",
      iso_alpha_3: "BIH",
      iso_numeric: 70,
    },
    {
      name: "Botswana",
      iso_alpha_2: "BW",
      iso_alpha_3: "BWA",
      iso_numeric: 72,
    },
    { name: "Brazil", iso_alpha_2: "BR", iso_alpha_3: "BRA", iso_numeric: 76 },
    {
      name: "Brunei Darussalam",
      iso_alpha_2: "BN",
      iso_alpha_3: "BRN",
      iso_numeric: 96,
    },
    {
      name: "Bulgaria",
      iso_alpha_2: "BG",
      iso_alpha_3: "BGR",
      iso_numeric: 100,
    },
    {
      name: "Burkina Faso",
      iso_alpha_2: "BF",
      iso_alpha_3: "BFA",
      iso_numeric: 854,
    },
    {
      name: "Burundi",
      iso_alpha_2: "BI",
      iso_alpha_3: "BDI",
      iso_numeric: 108,
    },
    {
      name: "Cabo Verde",
      iso_alpha_2: "CV",
      iso_alpha_3: "CPV",
      iso_numeric: 132,
    },
    {
      name: "Cambodia",
      iso_alpha_2: "KH",
      iso_alpha_3: "KHM",
      iso_numeric: 116,
    },
    {
      name: "Cameroon",
      iso_alpha_2: "CM",
      iso_alpha_3: "CMR",
      iso_numeric: 120,
    },
    { name: "Canada", iso_alpha_2: "CA", iso_alpha_3: "CAN", iso_numeric: 124 },
    {
      name: "Central African Republic",
      iso_alpha_2: "CF",
      iso_alpha_3: "CAF",
      iso_numeric: 140,
    },
    { name: "Chad", iso_alpha_2: "TD", iso_alpha_3: "TCD", iso_numeric: 148 },
    { name: "Chile", iso_alpha_2: "CL", iso_alpha_3: "CHL", iso_numeric: 152 },
    { name: "China", iso_alpha_2: "CN", iso_alpha_3: "CHN", iso_numeric: 156 },
    {
      name: "Colombia",
      iso_alpha_2: "CO",
      iso_alpha_3: "COL",
      iso_numeric: 170,
    },
    {
      name: "Comoros",
      iso_alpha_2: "KM",
      iso_alpha_3: "COM",
      iso_numeric: 174,
    },
    { name: "Congo", iso_alpha_2: "CG", iso_alpha_3: "COG", iso_numeric: 178 },
    {
      name: "Congo, Democratic Republic of the",
      iso_alpha_2: "CD",
      iso_alpha_3: "COD",
      iso_numeric: 180,
    },
    {
      name: "Costa Rica",
      iso_alpha_2: "CR",
      iso_alpha_3: "CRI",
      iso_numeric: 188,
    },
    {
      name: "Croatia",
      iso_alpha_2: "HR",
      iso_alpha_3: "HRV",
      iso_numeric: 191,
    },
    { name: "Cuba", iso_alpha_2: "CU", iso_alpha_3: "CUB", iso_numeric: 192 },
    { name: "Cyprus", iso_alpha_2: "CY", iso_alpha_3: "CYP", iso_numeric: 196 },
    {
      name: "Czech Republic",
      iso_alpha_2: "CZ",
      iso_alpha_3: "CZE",
      iso_numeric: 203,
    },
    {
      name: "Denmark",
      iso_alpha_2: "DK",
      iso_alpha_3: "DNK",
      iso_numeric: 208,
    },
    {
      name: "Djibouti",
      iso_alpha_2: "DJ",
      iso_alpha_3: "DJI",
      iso_numeric: 262,
    },
    {
      name: "Dominica",
      iso_alpha_2: "DM",
      iso_alpha_3: "DMA",
      iso_numeric: 212,
    },
    {
      name: "Dominican Republic",
      iso_alpha_2: "DO",
      iso_alpha_3: "DOM",
      iso_numeric: 214,
    },
    {
      name: "Ecuador",
      iso_alpha_2: "EC",
      iso_alpha_3: "ECU",
      iso_numeric: 218,
    },
    { name: "Egypt", iso_alpha_2: "EG", iso_alpha_3: "EGY", iso_numeric: 818 },
    {
      name: "El Salvador",
      iso_alpha_2: "SV",
      iso_alpha_3: "SLV",
      iso_numeric: 222,
    },
    {
      name: "Equatorial Guinea",
      iso_alpha_2: "GQ",
      iso_alpha_3: "GNQ",
      iso_numeric: 226,
    },
    {
      name: "Eritrea",
      iso_alpha_2: "ER",
      iso_alpha_3: "ERI",
      iso_numeric: 232,
    },
    {
      name: "Estonia",
      iso_alpha_2: "EE",
      iso_alpha_3: "EST",
      iso_numeric: 233,
    },
    {
      name: "Eswatini",
      iso_alpha_2: "SZ",
      iso_alpha_3: "SWZ",
      iso_numeric: 748,
    },
    {
      name: "Ethiopia",
      iso_alpha_2: "ET",
      iso_alpha_3: "ETH",
      iso_numeric: 231,
    },
    { name: "Fiji", iso_alpha_2: "FJ", iso_alpha_3: "FJI", iso_numeric: 242 },
    {
      name: "Finland",
      iso_alpha_2: "FI",
      iso_alpha_3: "FIN",
      iso_numeric: 246,
    },
    { name: "France", iso_alpha_2: "FR", iso_alpha_3: "FRA", iso_numeric: 250 },
    { name: "Gabon", iso_alpha_2: "GA", iso_alpha_3: "GAB", iso_numeric: 266 },
    { name: "Gambia", iso_alpha_2: "GM", iso_alpha_3: "GMB", iso_numeric: 270 },
    {
      name: "Georgia",
      iso_alpha_2: "GE",
      iso_alpha_3: "GEO",
      iso_numeric: 268,
    },
    {
      name: "Germany",
      iso_alpha_2: "DE",
      iso_alpha_3: "DEU",
      iso_numeric: 276,
    },
    { name: "Ghana", iso_alpha_2: "GH", iso_alpha_3: "GHA", iso_numeric: 288 },
    { name: "Greece", iso_alpha_2: "GR", iso_alpha_3: "GRC", iso_numeric: 300 },
    {
      name: "Grenada",
      iso_alpha_2: "GD",
      iso_alpha_3: "GRD",
      iso_numeric: 308,
    },
    {
      name: "Guatemala",
      iso_alpha_2: "GT",
      iso_alpha_3: "GTM",
      iso_numeric: 320,
    },
    { name: "Guinea", iso_alpha_2: "GN", iso_alpha_3: "GIN", iso_numeric: 324 },
    {
      name: "Guinea-Bissau",
      iso_alpha_2: "GW",
      iso_alpha_3: "GNB",
      iso_numeric: 624,
    },
    { name: "Guyana", iso_alpha_2: "GY", iso_alpha_3: "GUY", iso_numeric: 328 },
    { name: "Haiti", iso_alpha_2: "HT", iso_alpha_3: "HTI", iso_numeric: 332 },
    {
      name: "Honduras",
      iso_alpha_2: "HN",
      iso_alpha_3: "HND",
      iso_numeric: 340,
    },
    {
      name: "Hungary",
      iso_alpha_2: "HU",
      iso_alpha_3: "HUN",
      iso_numeric: 348,
    },
    {
      name: "Iceland",
      iso_alpha_2: "IS",
      iso_alpha_3: "ISL",
      iso_numeric: 352,
    },
    { name: "India", iso_alpha_2: "IN", iso_alpha_3: "IND", iso_numeric: 356 },
    {
      name: "Indonesia",
      iso_alpha_2: "ID",
      iso_alpha_3: "IDN",
      iso_numeric: 360,
    },
    { name: "Iran", iso_alpha_2: "IR", iso_alpha_3: "IRN", iso_numeric: 364 },
    { name: "Iraq", iso_alpha_2: "IQ", iso_alpha_3: "IRQ", iso_numeric: 368 },
    {
      name: "Ireland",
      iso_alpha_2: "IE",
      iso_alpha_3: "IRL",
      iso_numeric: 372,
    },
    { name: "Israel", iso_alpha_2: "IL", iso_alpha_3: "ISR", iso_numeric: 376 },
    { name: "Italy", iso_alpha_2: "IT", iso_alpha_3: "ITA", iso_numeric: 380 },
    {
      name: "Jamaica",
      iso_alpha_2: "JM",
      iso_alpha_3: "JAM",
      iso_numeric: 388,
    },
    { name: "Japan", iso_alpha_2: "JP", iso_alpha_3: "JPN", iso_numeric: 392 },
    { name: "Jordan", iso_alpha_2: "JO", iso_alpha_3: "JOR", iso_numeric: 400 },
    {
      name: "Kazakhstan",
      iso_alpha_2: "KZ",
      iso_alpha_3: "KAZ",
      iso_numeric: 398,
    },
    { name: "Kenya", iso_alpha_2: "KE", iso_alpha_3: "KEN", iso_numeric: 404 },
    {
      name: "Kiribati",
      iso_alpha_2: "KI",
      iso_alpha_3: "KIR",
      iso_numeric: 296,
    },
    {
      name: "Korea, Democratic People's Republic of",
      iso_alpha_2: "KP",
      iso_alpha_3: "PRK",
      iso_numeric: 408,
    },
    {
      name: "Korea, Republic of",
      iso_alpha_2: "KR",
      iso_alpha_3: "KOR",
      iso_numeric: 410,
    },
    { name: "Kuwait", iso_alpha_2: "KW", iso_alpha_3: "KWT", iso_numeric: 414 },
    {
      name: "Kyrgyzstan",
      iso_alpha_2: "KG",
      iso_alpha_3: "KGZ",
      iso_numeric: 417,
    },
    {
      name: "Lao People's Democratic Republic",
      iso_alpha_2: "LA",
      iso_alpha_3: "LAO",
      iso_numeric: 418,
    },
    { name: "Latvia", iso_alpha_2: "LV", iso_alpha_3: "LVA", iso_numeric: 428 },
    {
      name: "Lebanon",
      iso_alpha_2: "LB",
      iso_alpha_3: "LBN",
      iso_numeric: 422,
    },
    {
      name: "Lesotho",
      iso_alpha_2: "LS",
      iso_alpha_3: "LSO",
      iso_numeric: 426,
    },
    {
      name: "Liberia",
      iso_alpha_2: "LR",
      iso_alpha_3: "LBR",
      iso_numeric: 430,
    },
    { name: "Libya", iso_alpha_2: "LY", iso_alpha_3: "LBY", iso_numeric: 434 },
    {
      name: "Liechtenstein",
      iso_alpha_2: "LI",
      iso_alpha_3: "LIE",
      iso_numeric: 438,
    },
    {
      name: "Lithuania",
      iso_alpha_2: "LT",
      iso_alpha_3: "LTU",
      iso_numeric: 440,
    },
    {
      name: "Luxembourg",
      iso_alpha_2: "LU",
      iso_alpha_3: "LUX",
      iso_numeric: 442,
    },
    {
      name: "Madagascar",
      iso_alpha_2: "MG",
      iso_alpha_3: "MDG",
      iso_numeric: 450,
    },
    { name: "Malawi", iso_alpha_2: "MW", iso_alpha_3: "MWI", iso_numeric: 454 },
    {
      name: "Malaysia",
      iso_alpha_2: "MY",
      iso_alpha_3: "MYS",
      iso_numeric: 458,
    },
    {
      name: "Maldives",
      iso_alpha_2: "MV",
      iso_alpha_3: "MDV",
      iso_numeric: 462,
    },
    { name: "Mali", iso_alpha_2: "ML", iso_alpha_3: "MLI", iso_numeric: 466 },
    { name: "Malta", iso_alpha_2: "MT", iso_alpha_3: "MLT", iso_numeric: 470 },
    {
      name: "Marshall Islands",
      iso_alpha_2: "MH",
      iso_alpha_3: "MHL",
      iso_numeric: 584,
    },
    {
      name: "Mauritania",
      iso_alpha_2: "MR",
      iso_alpha_3: "MRT",
      iso_numeric: 478,
    },
    {
      name: "Mauritius",
      iso_alpha_2: "MU",
      iso_alpha_3: "MUS",
      iso_numeric: 480,
    },
    { name: "Mexico", iso_alpha_2: "MX", iso_alpha_3: "MEX", iso_numeric: 484 },
    {
      name: "Micronesia (Federated States of)",
      iso_alpha_2: "FM",
      iso_alpha_3: "FSM",
      iso_numeric: 583,
    },
    {
      name: "Moldova (Republic of)",
      iso_alpha_2: "MD",
      iso_alpha_3: "MDA",
      iso_numeric: 498,
    },
    { name: "Monaco", iso_alpha_2: "MC", iso_alpha_3: "MCO", iso_numeric: 492 },
    {
      name: "Mongolia",
      iso_alpha_2: "MN",
      iso_alpha_3: "MNG",
      iso_numeric: 496,
    },
    {
      name: "Montenegro",
      iso_alpha_2: "ME",
      iso_alpha_3: "MNE",
      iso_numeric: 499,
    },
    {
      name: "Morocco",
      iso_alpha_2: "MA",
      iso_alpha_3: "MAR",
      iso_numeric: 504,
    },
    {
      name: "Mozambique",
      iso_alpha_2: "MZ",
      iso_alpha_3: "MOZ",
      iso_numeric: 508,
    },
    {
      name: "Myanmar",
      iso_alpha_2: "MM",
      iso_alpha_3: "MMR",
      iso_numeric: 104,
    },
    {
      name: "Namibia",
      iso_alpha_2: "NA",
      iso_alpha_3: "NAM",
      iso_numeric: 516,
    },
    { name: "Nauru", iso_alpha_2: "NR", iso_alpha_3: "NRU", iso_numeric: 520 },
    { name: "Nepal", iso_alpha_2: "NP", iso_alpha_3: "NPL", iso_numeric: 524 },
    {
      name: "Netherlands",
      iso_alpha_2: "NL",
      iso_alpha_3: "NLD",
      iso_numeric: 528,
    },
    {
      name: "New Zealand",
      iso_alpha_2: "NZ",
      iso_alpha_3: "NZL",
      iso_numeric: 554,
    },
    {
      name: "Nicaragua",
      iso_alpha_2: "NI",
      iso_alpha_3: "NIC",
      iso_numeric: 558,
    },
    { name: "Niger", iso_alpha_2: "NE", iso_alpha_3: "NER", iso_numeric: 562 },
    {
      name: "Nigeria",
      iso_alpha_2: "NG",
      iso_alpha_3: "NGA",
      iso_numeric: 566,
    },
    {
      name: "North Macedonia",
      iso_alpha_2: "MK",
      iso_alpha_3: "MKD",
      iso_numeric: 807,
    },
    { name: "Norway", iso_alpha_2: "NO", iso_alpha_3: "NOR", iso_numeric: 578 },
    { name: "Oman", iso_alpha_2: "OM", iso_alpha_3: "OMN", iso_numeric: 512 },
    {
      name: "Pakistan",
      iso_alpha_2: "PK",
      iso_alpha_3: "PAK",
      iso_numeric: 586,
    },
    { name: "Palau", iso_alpha_2: "PW", iso_alpha_3: "PLW", iso_numeric: 585 },
    { name: "Panama", iso_alpha_2: "PA", iso_alpha_3: "PAN", iso_numeric: 591 },
    {
      name: "Papua New Guinea",
      iso_alpha_2: "PG",
      iso_alpha_3: "PNG",
      iso_numeric: 598,
    },
    {
      name: "Paraguay",
      iso_alpha_2: "PY",
      iso_alpha_3: "PRY",
      iso_numeric: 600,
    },
    { name: "Peru", iso_alpha_2: "PE", iso_alpha_3: "PER", iso_numeric: 604 },
    {
      name: "Philippines",
      iso_alpha_2: "PH",
      iso_alpha_3: "PHL",
      iso_numeric: 608,
    },
    { name: "Poland", iso_alpha_2: "PL", iso_alpha_3: "POL", iso_numeric: 616 },
    {
      name: "Portugal",
      iso_alpha_2: "PT",
      iso_alpha_3: "PRT",
      iso_numeric: 620,
    },
    { name: "Qatar", iso_alpha_2: "QA", iso_alpha_3: "QAT", iso_numeric: 634 },
    {
      name: "Romania",
      iso_alpha_2: "RO",
      iso_alpha_3: "ROU",
      iso_numeric: 642,
    },
    {
      name: "Russian Federation",
      iso_alpha_2: "RU",
      iso_alpha_3: "RUS",
      iso_numeric: 643,
    },
    { name: "Rwanda", iso_alpha_2: "RW", iso_alpha_3: "RWA", iso_numeric: 646 },
    {
      name: "Saint Kitts and Nevis",
      iso_alpha_2: "KN",
      iso_alpha_3: "KNA",
      iso_numeric: 659,
    },
    {
      name: "Saint Lucia",
      iso_alpha_2: "LC",
      iso_alpha_3: "LCA",
      iso_numeric: 662,
    },
    {
      name: "Saint Vincent and the Grenadines",
      iso_alpha_2: "VC",
      iso_alpha_3: "VCT",
      iso_numeric: 670,
    },
    { name: "Samoa", iso_alpha_2: "WS", iso_alpha_3: "WSM", iso_numeric: 882 },
    {
      name: "San Marino",
      iso_alpha_2: "SM",
      iso_alpha_3: "SMR",
      iso_numeric: 674,
    },
    {
      name: "Sao Tome and Principe",
      iso_alpha_2: "ST",
      iso_alpha_3: "STP",
      iso_numeric: 678,
    },
    {
      name: "Saudi Arabia",
      iso_alpha_2: "SA",
      iso_alpha_3: "SAU",
      iso_numeric: 682,
    },
    {
      name: "Senegal",
      iso_alpha_2: "SN",
      iso_alpha_3: "SEN",
      iso_numeric: 686,
    },
    { name: "Serbia", iso_alpha_2: "RS", iso_alpha_3: "SRB", iso_numeric: 688 },
    {
      name: "Seychelles",
      iso_alpha_2: "SC",
      iso_alpha_3: "SYC",
      iso_numeric: 690,
    },
    {
      name: "Sierra Leone",
      iso_alpha_2: "SL",
      iso_alpha_3: "SLE",
      iso_numeric: 694,
    },
    {
      name: "Singapore",
      iso_alpha_2: "SG",
      iso_alpha_3: "SGP",
      iso_numeric: 702,
    },
    {
      name: "Slovakia",
      iso_alpha_2: "SK",
      iso_alpha_3: "SVK",
      iso_numeric: 703,
    },
    {
      name: "Slovenia",
      iso_alpha_2: "SI",
      iso_alpha_3: "SVN",
      iso_numeric: 705,
    },
    {
      name: "Solomon Islands",
      iso_alpha_2: "SB",
      iso_alpha_3: "SLB",
      iso_numeric: 90,
    },
    {
      name: "Somalia",
      iso_alpha_2: "SO",
      iso_alpha_3: "SOM",
      iso_numeric: 706,
    },
    {
      name: "South Africa",
      iso_alpha_2: "ZA",
      iso_alpha_3: "ZAF",
      iso_numeric: 710,
    },
    {
      name: "South Sudan",
      iso_alpha_2: "SS",
      iso_alpha_3: "SSD",
      iso_numeric: 728,
    },
    { name: "Spain", iso_alpha_2: "ES", iso_alpha_3: "ESP", iso_numeric: 724 },
    {
      name: "Sri Lanka",
      iso_alpha_2: "LK",
      iso_alpha_3: "LKA",
      iso_numeric: 144,
    },
    { name: "Sudan", iso_alpha_2: "SD", iso_alpha_3: "SDN", iso_numeric: 729 },
    {
      name: "Suriname",
      iso_alpha_2: "SR",
      iso_alpha_3: "SUR",
      iso_numeric: 740,
    },
    { name: "Sweden", iso_alpha_2: "SE", iso_alpha_3: "SWE", iso_numeric: 752 },
    {
      name: "Switzerland",
      iso_alpha_2: "CH",
      iso_alpha_3: "CHE",
      iso_numeric: 756,
    },
    {
      name: "Syrian Arab Republic",
      iso_alpha_2: "SY",
      iso_alpha_3: "SYR",
      iso_numeric: 760,
    },
    {
      name: "Tajikistan",
      iso_alpha_2: "TJ",
      iso_alpha_3: "TJK",
      iso_numeric: 762,
    },
    {
      name: "Tanzania, United Republic of",
      iso_alpha_2: "TZ",
      iso_alpha_3: "TZA",
      iso_numeric: 834,
    },
    {
      name: "Thailand",
      iso_alpha_2: "TH",
      iso_alpha_3: "THA",
      iso_numeric: 764,
    },
    {
      name: "Timor-Leste",
      iso_alpha_2: "TL",
      iso_alpha_3: "TLS",
      iso_numeric: 626,
    },
    { name: "Togo", iso_alpha_2: "TG", iso_alpha_3: "TGO", iso_numeric: 768 },
    { name: "Tonga", iso_alpha_2: "TO", iso_alpha_3: "TON", iso_numeric: 776 },
    {
      name: "Trinidad and Tobago",
      iso_alpha_2: "TT",
      iso_alpha_3: "TTO",
      iso_numeric: 780,
    },
    {
      name: "Tunisia",
      iso_alpha_2: "TN",
      iso_alpha_3: "TUN",
      iso_numeric: 788,
    },
    { name: "Turkey", iso_alpha_2: "TR", iso_alpha_3: "TUR", iso_numeric: 792 },
    {
      name: "Turkmenistan",
      iso_alpha_2: "TM",
      iso_alpha_3: "TKM",
      iso_numeric: 795,
    },
    { name: "Tuvalu", iso_alpha_2: "TV", iso_alpha_3: "TUV", iso_numeric: 798 },
    { name: "Uganda", iso_alpha_2: "UG", iso_alpha_3: "UGA", iso_numeric: 800 },
    {
      name: "Ukraine",
      iso_alpha_2: "UA",
      iso_alpha_3: "UKR",
      iso_numeric: 804,
    },
    {
      name: "United Arab Emirates",
      iso_alpha_2: "AE",
      iso_alpha_3: "ARE",
      iso_numeric: 784,
    },
    {
      name: "United Kingdom of Great Britain and Northern Ireland",
      iso_alpha_2: "GB",
      iso_alpha_3: "GBR",
      iso_numeric: 826,
    },
    {
      name: "United States of America",
      iso_alpha_2: "US",
      iso_alpha_3: "USA",
      iso_numeric: 840,
    },
    {
      name: "Uruguay",
      iso_alpha_2: "UY",
      iso_alpha_3: "URY",
      iso_numeric: 858,
    },
    {
      name: "Uzbekistan",
      iso_alpha_2: "UZ",
      iso_alpha_3: "UZB",
      iso_numeric: 860,
    },
    {
      name: "Vanuatu",
      iso_alpha_2: "VU",
      iso_alpha_3: "VUT",
      iso_numeric: 548,
    },
    {
      name: "Venezuela (Bolivarian Republic of)",
      iso_alpha_2: "VE",
      iso_alpha_3: "VEN",
      iso_numeric: 862,
    },
    {
      name: "Viet Nam",
      iso_alpha_2: "VN",
      iso_alpha_3: "VNM",
      iso_numeric: 704,
    },
    { name: "Yemen", iso_alpha_2: "YE", iso_alpha_3: "YEM", iso_numeric: 887 },
    { name: "Zambia", iso_alpha_2: "ZM", iso_alpha_3: "ZMB", iso_numeric: 894 },
    {
      name: "Zimbabwe",
      iso_alpha_2: "ZW",
      iso_alpha_3: "ZWE",
      iso_numeric: 716,
    },
  ]);
};

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = async function (knex) {
  await knex.raw(down(tableName));
  return knex.schema.dropTable(tableName);
};
