/**
 * Error codes for API responses.
 * The frontend uses these codes for i18n translation.
 *
 * Convention: ENTITY_ACTION_RESULT
 * Example: USER_NOT_FOUND, PAYMENT_CREATION_FAILED
 */

module.exports = {
  // Generic errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Authentication
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
  AUTH_TOKEN_GENERATION_FAILED: "AUTH_TOKEN_GENERATION_FAILED",
  AUTH_CODE_NOT_FOUND: "AUTH_CODE_NOT_FOUND",
  AUTH_EMAIL_SEND_FAILED: "AUTH_EMAIL_SEND_FAILED",
  AUTH_WHATSAPP_SEND_FAILED: "AUTH_WHATSAPP_SEND_FAILED",
  AUTH_RECOVERY_CODE_CREATION_FAILED: "AUTH_RECOVERY_CODE_CREATION_FAILED",
  AUTH_ACCOUNT_BLOCKED: "AUTH_ACCOUNT_BLOCKED",
  AUTH_RATE_LIMIT: "AUTH_RATE_LIMIT",
  AUTH_HOURLY_LIMIT: "AUTH_HOURLY_LIMIT",
  AUTH_VERIFICATION_ATTEMPTS_FAILED: "AUTH_VERIFICATION_ATTEMPTS_FAILED",

  // Accounts
  ACCOUNT_CREATION_FAILED: "ACCOUNT_CREATION_FAILED",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  ACCOUNT_EMAIL_NOT_FOUND: "ACCOUNT_EMAIL_NOT_FOUND",
  ACCOUNT_PHONE_ALREADY_EXISTS: "ACCOUNT_PHONE_ALREADY_EXISTS",
  ACCOUNT_EMAIL_ALREADY_EXISTS: "ACCOUNT_EMAIL_ALREADY_EXISTS",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
  ACCOUNT_UPDATE_FAILED: "ACCOUNT_UPDATE_FAILED",
  ACCOUNT_PERMISSION_DENIED: "ACCOUNT_PERMISSION_DENIED",
  ACCOUNT_CARD_NOT_FOUND: "ACCOUNT_CARD_NOT_FOUND",
  ACCOUNT_CARD_ALREADY_EXISTS: "ACCOUNT_CARD_ALREADY_EXISTS",
  ACCOUNT_CARD_INVALID_EXPIRATION: "ACCOUNT_CARD_INVALID_EXPIRATION",
  ACCOUNT_CARD_EXPIRED: "ACCOUNT_CARD_EXPIRED",
  ACCOUNT_CARD_CREATION_FAILED: "ACCOUNT_CARD_CREATION_FAILED",
  ACCOUNT_CARD_DELETION_FAILED: "ACCOUNT_CARD_DELETION_FAILED",

  // Bots
  BOT_NOT_FOUND: "BOT_NOT_FOUND",
  BOT_SOCIAL_NETWORK_NOT_ACTIVATED: "BOT_SOCIAL_NETWORK_NOT_ACTIVATED",
  BOT_INSTANCE_NOT_FOUND: "BOT_INSTANCE_NOT_FOUND",
  BOT_INCORRECT_IDENTIFIER: "BOT_INCORRECT_IDENTIFIER",
  BOT_EMPTY_IDENTIFIER: "BOT_EMPTY_IDENTIFIER",

  // Company
  COMPANY_NOT_FOUND: "COMPANY_NOT_FOUND",

  // Network
  NETWORK_NOT_FOUND: "NETWORK_NOT_FOUND",

  // Prompts
  PROMPT_NOT_FOUND: "PROMPT_NOT_FOUND",
  PROMPT_CREATION_FAILED: "PROMPT_CREATION_FAILED",
  PROMPT_DELETE_ACTIVE_DENIED: "PROMPT_DELETE_ACTIVE_DENIED",

  // Roles
  ROLE_INVALID: "ROLE_INVALID",

  // Webhooks
  WEBHOOK_INVALID_SNS_TOPIC: "WEBHOOK_INVALID_SNS_TOPIC",
  WEBHOOK_VERIFICATION_FAILED: "WEBHOOK_VERIFICATION_FAILED",

  // Pinecone
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  FILE_ALREADY_DISABLED: "FILE_ALREADY_DISABLED",
  INDEX_NOT_FOUND: "INDEX_NOT_FOUND",
  DISABLED_FILE_NOT_FOUND: "DISABLED_FILE_NOT_FOUND",

  // Short URLs
  URL_NOT_FOUND: "URL_NOT_FOUND",
  URL_EXPIRED: "URL_EXPIRED",
  URL_ATTEMPTS_EXHAUSTED: "URL_ATTEMPTS_EXHAUSTED",
  URL_GET_FAILED: "URL_GET_FAILED",
  URL_INSERT_FAILED: "URL_INSERT_FAILED",
  URL_SAVE_FAILED: "URL_SAVE_FAILED",
  URL_UPDATE_FAILED: "URL_UPDATE_FAILED",
  URL_UPDATE_NOT_FOUND: "URL_UPDATE_NOT_FOUND",

  // Social
  SOCIAL_NETWORK_NOT_FOUND: "SOCIAL_NETWORK_NOT_FOUND",
  SOCIAL_NETWORK_PROVIDER_NOT_FOUND: "SOCIAL_NETWORK_PROVIDER_NOT_FOUND",
  WHATSAPP_EVENT_NOT_FOUND: "WHATSAPP_EVENT_NOT_FOUND",
  CONTACT_NOT_FOUND: "CONTACT_NOT_FOUND",

  // Storage
  STORAGE_NOT_FOUND: "STORAGE_NOT_FOUND",
  STORAGE_LOG_NOT_FOUND: "STORAGE_LOG_NOT_FOUND",
  STORAGE_CREATION_FAILED: "STORAGE_CREATION_FAILED",
  STORAGE_UPDATE_FAILED: "STORAGE_UPDATE_FAILED",
  STORAGE_DELETION_FAILED: "STORAGE_DELETION_FAILED",
  STORAGE_ALREADY_EXISTS: "STORAGE_ALREADY_EXISTS",
  STORAGE_INSUFFICIENT_SPACE: "STORAGE_INSUFFICIENT_SPACE",
  STORAGE_INVALID_QUOTA: "STORAGE_INVALID_QUOTA",
  STORAGE_BUCKET_NOT_FOUND: "STORAGE_BUCKET_NOT_FOUND",
  STORAGE_BUCKET_CREATION_FAILED: "STORAGE_BUCKET_CREATION_FAILED",
  STORAGE_BUCKET_DELETION_FAILED: "STORAGE_BUCKET_DELETION_FAILED",

  // System Prompts Error Codes
  SYSTEM_PROMPT_NOT_FOUND: "SYSTEM_PROMPT_NOT_FOUND",
  SYSTEM_PROMPT_KEY_ALREADY_EXISTS: "SYSTEM_PROMPT_KEY_ALREADY_EXISTS",
  SYSTEM_PROMPT_PARENT_NOT_FOUND: "SYSTEM_PROMPT_PARENT_NOT_FOUND",
  SYSTEM_PROMPT_MAX_DEPTH_EXCEEDED: "SYSTEM_PROMPT_MAX_DEPTH_EXCEEDED",
  SYSTEM_PROMPT_HAS_CHILDREN: "SYSTEM_PROMPT_HAS_CHILDREN",

  // Currency
  CURRENCY_NOT_FOUND: "CURRENCY_NOT_FOUND",

  // Plans
  PLAN_NAME_EXISTS: "PLAN_NAME_EXISTS",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_EXTENSION_NOT_FOUND: "PLAN_EXTENSION_NOT_FOUND",
  PLAN_EXTENSION_EXISTS: "PLAN_EXTENSION_EXISTS",

  // Extensions
  EXTENSION_NOT_FOUND: "EXTENSION_NOT_FOUND",

  // Yappy
  YAPPY_CONFIG_NOT_SET: "YAPPY_CONFIG_NOT_SET",
  YAPPY_INVALID_HASH: "YAPPY_INVALID_HASH",
  YAPPY_NOTIFY_FAILED: "YAPPY_NOTIFY_FAILED",

  // Payments
  PAYMENT_PROVIDER_NOT_FOUND: "PAYMENT_PROVIDER_NOT_FOUND",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
};
