module.exports = {
  BOT_EVENTS: {
    SAVE_MESSAGE_HISTORY: "save_message_history",
    UPDATE_PROMPT: "update_prompt",
    SET_COMPANY_CONFIGS: "set_company_configs",
    SAVE_BOT_CONFIG: "save_bot_config",
    START_CAMPAIGN: "start_campaign",
    SET_CALL_CENTER_DEPARTMENTS: "set_call_center_departments",
    SEND_MESSAGE: "send_message",
    SEND_MESSAGE_TO_WHITELIST: "send_message_to_whitelist",
    GET_BOT_INFO: "get_bot_info",
    DELETE_BOT_EXTENSION_CONFIGS: "delete_bot_extension_configs",
    SET_BOT_WHITELIST: "set_bot_whitelist",
    SET_BOT_BLACKLIST: "set_bot_blacklist",
    SET_RAG_CONFIGS: "set_rag_configs",
    GET_CHAT_STATUS: "get_chat_status",
    UPDATE_CHAT_STATUS: "update_chat_status",
    SEND_CAMPAIGN_MESSAGE: "send_campaign_message",
    UPDATE_CAMPAIGN_STATUS: "update_campaign_status",
    SAVE_BOT_DATA: "save_bot_data",
    MESSAGE_QUEUE: "message_queue",
    DISCONNECT_CLIENT: "disconnect_client",
  },
  ORCHESTATOR_EVENTS: {
    RESTART_BOT: "restartBot",
    STOP_BOT: "stopBot",
    DELETE_BOT: "deleteBot",
    START_BOT: "startBot",
    INITIALIZE_BOT: "initializeBOT",
    CANCEL_INITIALIZATION_BOT: "cancelInitializationBOT",
  },
};
